apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-role
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods/metrics", "nodes/*", "services", "endpoints","nodes","pods"]
  verbs: ["get", "list", "watch"]
