apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: web-app
        image: granitfazliudev/solab-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "flaskr"
        - name: FLASK_ENV
          value: "development"
