apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-time-cron
spec:
  schedule: "*/10 * * * *"  # Run every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-time
            image: busybox
            args:
            - /bin/sh
            - -c
            - date  # Command to print the current date and time
          restartPolicy: OnFailure
